apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    kubernetes.io/metadata.name: demoapp
  name: demoapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  namespace: demoapp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - image: argoproj/rollouts-demo:green
        name: demoapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp 
  namespace: demoapp
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31001
  selector:
    app: demoapp
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demoapp-gateway
  namespace: demoapp
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demoapp-vsvc
  namespace: demoapp
spec:
  gateways:
  - demoapp/demoapp-gateway
  hosts:
  - demoapp.127.0.0.1.nip.io
  http:
  - name: primary
    route:
    - destination:
        host: demoapp 
      weight: 100
